+incdir+/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src

/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/cache/cacheblock/std_dffr.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/cache/cacheblock/std_dffe.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/cache/cacheblock/sky130_sram_1rw1r_64x256_8.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/cache/cacheblock/sky130_sram_1kbyte_1rw1r_32x256_8.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/cache/l1icache_32.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/cache/l1dcache.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/lsu/ac.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/lsu/agu.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/lsu/cu.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/lsu/lsq.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/lsu/lr.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/lsu/nblsu.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/btb.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/counter_rob.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/counter_tmp.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/counter.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/csr.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/decode.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/excep_ctrl.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/fetch.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/fifo_tmp.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/fifo.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/gshare.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/ins_buffer.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/new_alu.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/new_fu.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/physical_regfile.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/units/rcu.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/pipeline/frontend.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/pipeline/backend.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/core_empty/core_empty.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/bus_arbiter.v
/work/stu/zxluan/RIOS_lab/riosclass_template/verilog/rtl/lab_1/src/hehe.v
/work/stu/zxluan/RIOS_lab/riosclass_template/co-sim/cosim.cpp
./dpram64.sv
./wb_arb.sv
./wb_interconnect.sv
./hehe_tb.sv


